name: Quality check
on:
  push:
    branches-ignore:
      - master
jobs:
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
  build:
    name: Build artifacts
    needs: [commitlint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
  test:
    name: Test code
    needs: [commitlint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
  lint:
    name: Lint code
    needs: [commitlint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint
